--- #Optional YAML start syntax
- name: Run a private node image as docker cointainer
  docker_container:
    name: node
    image: "runitcr/dcc:latest"
    ports: "6869:6869"
    state: started
    
- name: Run a blockchain explorer image as docker cointainer
  docker_container:    
    name: explorer
    image: "blockchaincostarica/explorer:3.3.0"
    ports: "3000:8080"
    state: started
    env: 
      API_NODE_URL: http://localhost:6869
      NODE_LIST: http://localhost:6869